# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_madmin import generic_pb2 as grpc__madmin_dot_generic__pb2
from grpc_madmin import invite_pb2 as grpc__madmin_dot_invite__pb2


class InviteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoUserInvites = channel.unary_unary(
                '/grpc_madmin.invite.InviteService/DoUserInvites',
                request_serializer=grpc__madmin_dot_invite__pb2.UserInviteRequest.SerializeToString,
                response_deserializer=grpc__madmin_dot_generic__pb2.GenericResponse.FromString,
                )


class InviteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoUserInvites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InviteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoUserInvites': grpc.unary_unary_rpc_method_handler(
                    servicer.DoUserInvites,
                    request_deserializer=grpc__madmin_dot_invite__pb2.UserInviteRequest.FromString,
                    response_serializer=grpc__madmin_dot_generic__pb2.GenericResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_madmin.invite.InviteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InviteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoUserInvites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_madmin.invite.InviteService/DoUserInvites',
            grpc__madmin_dot_invite__pb2.UserInviteRequest.SerializeToString,
            grpc__madmin_dot_generic__pb2.GenericResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
