# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: grpc_madmin/invite.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import grpc_madmin.generic_pb2
import grpc_madmin.invite_pb2


class InviteServiceBase(abc.ABC):

    @abc.abstractmethod
    async def DoUserInvites(self, stream: 'grpclib.server.Stream[grpc_madmin.invite_pb2.UserInviteRequest, grpc_madmin.generic_pb2.GenericResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/grpc_madmin.invite.InviteService/DoUserInvites': grpclib.const.Handler(
                self.DoUserInvites,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc_madmin.invite_pb2.UserInviteRequest,
                grpc_madmin.generic_pb2.GenericResponse,
            ),
        }


class InviteServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.DoUserInvites = grpclib.client.UnaryUnaryMethod(
            channel,
            '/grpc_madmin.invite.InviteService/DoUserInvites',
            grpc_madmin.invite_pb2.UserInviteRequest,
            grpc_madmin.generic_pb2.GenericResponse,
        )
