# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpc_madmin import generic_pb2 as grpc__madmin_dot_generic__pb2
from grpc_madmin import invite_pb2 as grpc__madmin_dot_invite__pb2


class InviteServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DoUserInvites = channel.unary_unary(
        '/grpc_madmin.invite.InviteService/DoUserInvites',
        request_serializer=grpc__madmin_dot_invite__pb2.UserInviteRequest.SerializeToString,
        response_deserializer=grpc__madmin_dot_generic__pb2.GenericResponse.FromString,
        )


class InviteServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DoUserInvites(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InviteServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DoUserInvites': grpc.unary_unary_rpc_method_handler(
          servicer.DoUserInvites,
          request_deserializer=grpc__madmin_dot_invite__pb2.UserInviteRequest.FromString,
          response_serializer=grpc__madmin_dot_generic__pb2.GenericResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc_madmin.invite.InviteService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
