# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_madmin/invite.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_madmin import generic_pb2 as grpc__madmin_dot_generic__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_madmin/invite.proto',
  package='grpc_madmin.invite',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x18grpc_madmin/invite.proto\x12\x12grpc_madmin.invite\x1a\x19grpc_madmin/generic.proto\"N\n\x11UserInviteRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ndiscord_id\x18\x02 \x01(\x03\x12\x0f\n\x07\x61uth_id\x18\x03 \x01(\x05\x32m\n\rInviteService\x12\\\n\rDoUserInvites\x12%.grpc_madmin.invite.UserInviteRequest\x1a$.grpc_madmin.generic.GenericResponseb\x06proto3'
  ,
  dependencies=[grpc__madmin_dot_generic__pb2.DESCRIPTOR,])




_USERINVITEREQUEST = _descriptor.Descriptor(
  name='UserInviteRequest',
  full_name='grpc_madmin.invite.UserInviteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='access_token', full_name='grpc_madmin.invite.UserInviteRequest.access_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='discord_id', full_name='grpc_madmin.invite.UserInviteRequest.discord_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth_id', full_name='grpc_madmin.invite.UserInviteRequest.auth_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['UserInviteRequest'] = _USERINVITEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserInviteRequest = _reflection.GeneratedProtocolMessageType('UserInviteRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERINVITEREQUEST,
  '__module__' : 'grpc_madmin.invite_pb2'
  # @@protoc_insertion_point(class_scope:grpc_madmin.invite.UserInviteRequest)
  })
_sym_db.RegisterMessage(UserInviteRequest)



_INVITESERVICE = _descriptor.ServiceDescriptor(
  name='InviteService',
  full_name='grpc_madmin.invite.InviteService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=155,
  serialized_end=264,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoUserInvites',
    full_name='grpc_madmin.invite.InviteService.DoUserInvites',
    index=0,
    containing_service=None,
    input_type=_USERINVITEREQUEST,
    output_type=grpc__madmin_dot_generic__pb2._GENERICRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INVITESERVICE)

DESCRIPTOR.services_by_name['InviteService'] = _INVITESERVICE

# @@protoc_insertion_point(module_scope)
