# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_madmin/invite.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_madmin import generic_pb2 as grpc__madmin_dot_generic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grpc_madmin/invite.proto\x12\x12grpc_madmin.invite\x1a\x19grpc_madmin/generic.proto\"N\n\x11UserInviteRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ndiscord_id\x18\x02 \x01(\x03\x12\x0f\n\x07\x61uth_id\x18\x03 \x01(\x05\x32m\n\rInviteService\x12\\\n\rDoUserInvites\x12%.grpc_madmin.invite.UserInviteRequest\x1a$.grpc_madmin.generic.GenericResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_madmin.invite_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERINVITEREQUEST._serialized_start=75
  _USERINVITEREQUEST._serialized_end=153
  _INVITESERVICE._serialized_start=155
  _INVITESERVICE._serialized_end=264
# @@protoc_insertion_point(module_scope)
