# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_madmin/user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_madmin import generic_pb2 as grpc__madmin_dot_generic__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_madmin/user.proto',
  package='grpc_madmin.user',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16grpc_madmin/user.proto\x12\x10grpc_madmin.user\x1a\x19grpc_madmin/generic.proto\"\\\n\x11UserAccessUpdated\x12\x0f\n\x07\x61uth_id\x18\x01 \x01(\x05\x12\x10\n\x08sso_uuid\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x12\n\ndiscord_id\x18\x04 \x01(\x03\x32h\n\x0bUserService\x12Y\n\x0cOnUpdateUser\x12#.grpc_madmin.user.UserAccessUpdated\x1a$.grpc_madmin.generic.GenericResponseb\x06proto3')
  ,
  dependencies=[grpc__madmin_dot_generic__pb2.DESCRIPTOR,])




_USERACCESSUPDATED = _descriptor.Descriptor(
  name='UserAccessUpdated',
  full_name='grpc_madmin.user.UserAccessUpdated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth_id', full_name='grpc_madmin.user.UserAccessUpdated.auth_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sso_uuid', full_name='grpc_madmin.user.UserAccessUpdated.sso_uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='grpc_madmin.user.UserAccessUpdated.username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='discord_id', full_name='grpc_madmin.user.UserAccessUpdated.discord_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['UserAccessUpdated'] = _USERACCESSUPDATED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserAccessUpdated = _reflection.GeneratedProtocolMessageType('UserAccessUpdated', (_message.Message,), {
  'DESCRIPTOR' : _USERACCESSUPDATED,
  '__module__' : 'grpc_madmin.user_pb2'
  # @@protoc_insertion_point(class_scope:grpc_madmin.user.UserAccessUpdated)
  })
_sym_db.RegisterMessage(UserAccessUpdated)



_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='grpc_madmin.user.UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=165,
  serialized_end=269,
  methods=[
  _descriptor.MethodDescriptor(
    name='OnUpdateUser',
    full_name='grpc_madmin.user.UserService.OnUpdateUser',
    index=0,
    containing_service=None,
    input_type=_USERACCESSUPDATED,
    output_type=grpc__madmin_dot_generic__pb2._GENERICRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
