# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: grpc_madmin/utils.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import grpc_madmin.generic_pb2
import grpc_madmin.utils_pb2


class UtilsServiceBase(abc.ABC):

    @abc.abstractmethod
    async def GenerateRandomWords(self, stream: 'grpclib.server.Stream[grpc_madmin.utils_pb2.RandomWordsRequest, grpc_madmin.generic_pb2.GenericResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/grpc_madmin.utils.UtilsService/GenerateRandomWords': grpclib.const.Handler(
                self.GenerateRandomWords,
                grpclib.const.Cardinality.UNARY_UNARY,
                grpc_madmin.utils_pb2.RandomWordsRequest,
                grpc_madmin.generic_pb2.GenericResponse,
            ),
        }


class UtilsServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GenerateRandomWords = grpclib.client.UnaryUnaryMethod(
            channel,
            '/grpc_madmin.utils.UtilsService/GenerateRandomWords',
            grpc_madmin.utils_pb2.RandomWordsRequest,
            grpc_madmin.generic_pb2.GenericResponse,
        )
