# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_madmin/utils.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_madmin import generic_pb2 as grpc__madmin_dot_generic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17grpc_madmin/utils.proto\x12\x11grpc_madmin.utils\x1a\x19grpc_madmin/generic.proto\"5\n\x12RandomWordsRequest\x12\x0c\n\x04seed\x18\x01 \x01(\x03\x12\x11\n\tnum_words\x18\x02 \x01(\x05\x32r\n\x0cUtilsService\x12\x62\n\x13GenerateRandomWords\x12%.grpc_madmin.utils.RandomWordsRequest\x1a$.grpc_madmin.generic.GenericResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_madmin.utils_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RANDOMWORDSREQUEST._serialized_start=73
  _RANDOMWORDSREQUEST._serialized_end=126
  _UTILSSERVICE._serialized_start=128
  _UTILSSERVICE._serialized_end=242
# @@protoc_insertion_point(module_scope)
